
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp7_board(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire[7:0] a ,b ,c;
wire flag;

//=======================================================
//  Structural coding
//=======================================================


keyboard k(CLOCK_50,
	SW[0],//清零
	PS2_CLK,
	PS2_DAT,
	a,
	c,
	b,
   LEDR[0],//ctrl
   LEDR[1],//shift
	flag,
	LEDR[2]//caps
);

bcd7seg b0(
	 a[7:4],
	 HEX5,
	 1
	 );
	 
bcd7seg b1(
	 a[3:0],
	 HEX4,
	 1
	 );
	 
bcd7seg b2(
	 b[7:4],
	 HEX3,
	 flag
	 );
	 
bcd7seg b3(
	 b[3:0],
	 HEX2,
	 flag
	 );
	 
bcd7seg b4(
	 c[7:4],
	 HEX1,
	 flag
	 );
	 
bcd7seg b5(
	 c[3:0],
	 HEX0,
	 flag
	 );
	 


endmodule
