
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp4_board(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire clock;
divider di(CLOCK_50,clock);
wire [3:0] a;
wire [3:0] b;
counter co(clock,SW[0],SW[1],10,10,a,b,LEDR[0]);
bcd7seg bc(a,HEX0);
bcd7seg bc2(b,HEX1);

//=======================================================
//  Structural coding
//=======================================================



endmodule
