
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp6_board(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [7:0] a;
lfsr l(SW[7:0],
	KEY[0],
	a ,
	SW[9]
	);

bcd7seg b(
	 a[3:0],
	 HEX0
	 );
	 
bcd7seg b2(
	 a[7:4],
	 HEX1
	 );

//=======================================================
//  Structural coding
//=======================================================



endmodule
