
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp8_board(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,  //blue
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,  //green
	output		          		VGA_HS, //垂直同步 帧同步
	output		     [7:0]		VGA_R,  //red
	output		          		VGA_SYNC_N,//置零
	output		          		VGA_VS  //水平同步 行同步

);



//=======================================================
//  REG/WIRE declarations
//=======================================================

clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);

assign VGA_SYNC_N=0;


wire [9:0] h_addr;
wire [9:0] v_addr;
wire [18:0] addr={h_addr,v_addr[8:0]};
wire [11:0] vga_data;
rom ro(
	addr,
	VGA_CLK,
	vga_data);
	
vga_ctrl myvga(
VGA_CLK, //25MHz时钟
0, //置位
vga_data, // 上 层 模 块 提 供 的 VGA颜色数据
h_addr, // 提 供 给 上 层 模 块 的 当 前 扫 描 像 素 点 坐 标
v_addr,
VGA_HS, // 行 同 步 和 列 同 步 信 号
VGA_VS,
VGA_BLANK_N, //消隐信号
VGA_R, // 红 绿 蓝 颜 色 信 号
VGA_G,
VGA_B
 );

//=======================================================
//  Structural coding
//=======================================================



endmodule
